[Change] Raised the versions of rspec and rake respectively.
Because the following error occurs in rspec-core.
```
rake aborted!
NoMethodError: undefined method `last_comment' for #<Rake::Application:0x00007f9801855958>
/Library/Ruby/Gems/2.6.0/gems/rspec-core-2.14.8/lib/rspec/core/rake_task.rb:118:in `initialize'
```
`Line 16&17 of predictor.gemspec`

Since the version of rspec has been upgraded, I changed the matcher from be_true to be_truthy.
Since the version of rspec has been upgraded, I changed matcher from be_false to be_falsey.
`Line 42 of spec/base_spec.rb`

Since version 2.11 of Rspec, it is recommended to use expect syntax, so I fixed the test.
`Line 56 of spec/base_spec.rb`